### ISSUE TITLE
Video Link

### ISSUE THREAD

**Issue by vanitanaidu** [learn-co-curriculum/oo-ruby-video-object-orientation-overview#2] opened 2016-08-18 02:32 UTC
The link doesn't work

**Comment by gj** [comment] 2017-07-19 17:51
Hi @vanitanaidu !

The YouTube link seems to be working now. If you have a minute, would you mind verifying before I close this?

**Comment by curiositypaths** [comment] 2017-11-20 16:23
Hi there,

The YouTube link seems to be working now. If you are still not able to view the video please reopen the issue and provide the steps required to reproduce the issue

As always, thanks for contributing! 💙

**Closed as completed by curiositypaths** 2017-11-20 16:23 UTC
Labels: Product
