### ISSUE TITLE
The Video link does not work

### ISSUE THREAD

**Issue by kkterai** [learn-co-curriculum/oo-ruby-video-object-orientation-overview#1] opened 2016-08-16 22:59 UTC
I can't open this video, "OO Overview" using the link provided. Is there another?

**Comment by gj** [comment] 2017-07-19 17:51
Hi @kkterai !

The YouTube link seems to be working now. If you have a minute, would you mind verifying before I close this?

**Comment by curiositypaths** [comment] 2017-11-20 16:22
Hi there,

The YouTube link seems to be working now. If you are still not able to view the video please reopen the issue and provide the steps required to reproduce the issue

As always, thanks for contributing! 💙

**Closed as completed by curiositypaths** 2017-11-20 16:22 UTC
Labels: Curriculum
